~Version Information
 VERS.                  2.0 : CWLS log ASCII Standard -VERSION 2.0
 WRAP.                  NO  : One line per depth step
~Well Information
 STRT.M              1000.0 :
 STOP.M              1003.0 :
 STEP.M                 1.0 :
 NULL.              -999.25 :
 WELL.           7/11-1 A   : WELL
~Curve Information
 DEPT.M                     : DEPTH
 GR  .GAPI                  : Gamma Ray
~ASCII
1000.0   50.0
1001.0   80.0
1002.0  100.0
1003.0   60.0
